const DB_MODELS_EXTERNAL = {
    'athena': { 
        name: 'Athena', 
        type: 'relax', 
        folder: 'athena', 
        sizes: { S: 62, M: 72, L: 82, XL: 92 }, 
        meridienSizes: { S: 112, M: 122, L: 132, XL: 142 }, 
        chaiseSizes: { S: 62, M: 72, L: 82, XL: 92 },
        armWidth: 20, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 113, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r'] 
    },
    'bartini': { 
        name: 'Bartini', 
        type: 'relax', 
        folder: 'Bartini', 
        sizes: { S: 62, M: 68, L: 78, XL: 88 }, 
        meridienSizes: { S: 116, M: 122, L: 132, XL: 142 },
        chaiseSizes: { S: 62, M: 68, L: 78, XL: 88 },
        armWidth: 24, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 108, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r', 'meiple'] 
    },
    'brittany': { 
        name: 'Brittany', 
        type: 'relax', 
        folder: 'brittany', 
        sizes: { S: 62, M: 72, L: 82, XL: 92 }, 
        meridienSizes: { S: 112, M: 122, L: 132, XL: 142 }, 
        armWidth: 24, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 113, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r'] 
    },
    'dayma': { 
        name: 'Dayma', 
        type: 'relax', 
        folder: 'dayma', 
        sizes: { S: 62, M: 72, L: 82, XL: 92 }, 
        meridienSizes: { S: 112, M: 122, L: 132, XL: 142 }, 
        chaiseSizes: { S: 62, M: 72, L: 82, XL: 92 },
        armWidth: 24, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 113, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r'] 
    },
    'enzo': { 
        name: 'Enzo', 
        type: 'relax', 
        folder: 'enzo', 
        sizes: { S: 62, M: 72, L: 82, XL: 92 }, 
        meridienSizes: { S: 112, M: 122, L: 132, XL: 142 }, 
        chaiseSizes: { S: 92, M: 102, L: 112, XL: 122 },
        armWidth: 30, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 113, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r'] 
    },
    'fiori': { 
        name: 'Fiori', 
        type: 'relax', 
        folder: 'fiori', 
        sizes: { S: 62, M: 68, L: 78, XL: 88 }, 
        meridienSizes: { S: 114, M: 120, L: 130, XL: 140 }, 
        chaiseSizes: { S: 62, M: 68, L: 78, XL: 88 },
        armWidth: 25, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 108, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r'] 
    },
    'fienza': {
        name: 'Fienza',
        type: 'relax',
        folder: 'fienza',
        sizes: { S: 54, M: 64, L: 74, XL: 84 },
        armWidth: 28,
        depth: 97,
        chaiseDepth: 165,
        cornerSize: 112,
        modules: ['seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'corner']
    },
    'infinity': { name: 'Infinity (Deslizante)', type: 'slide', folder: 'Infinity', sizes: { S: 60, M: 67, L: 75, XL: 87, XXL: 97 }, armWidth: 17, depth: 110, chaiseDepth: 162, cornerSize: 0, modules: ['2seats_2arms', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', 'chaise_l', 'chaise_r', 'meiple'] },
    'magic': { name: 'Magic (Deslizante)', type: 'slide', folder: 'magic', sizes: { S: 60, M: 67, L: 75, XL: 87, XXL: 97 }, armWidth: 25, depth: 102, chaiseDepth: 154, cornerSize: 0, modules: ['2seats_2arms', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', 'chaise_l', 'chaise_r', 'meiple'] },
    'bruma': { 
        name: 'Bruma (Fixo)', 
        type: 'fixed', 
        folder: 'bruma', 
        sizes: { L: 83, XL: 111 }, 
        twoSeatSizes: { L: 166, XL: 185 },
        chaiseSizes: { L: 83, XL: 92 }, 
        pouffSize: 112,
        triangleSize: 110,
        triangleDepth: 108,
        armWidth: 23, 
        depth: 112, 
        chaiseDepth: 170, 
        cornerSize: 120, 
        modules: ['seat_arm_l', 'seat_arm_r', '2seats_no_arm', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'corner', 'triangle', 'pouff'] 
    },
    'kindia': { 
        name: 'Kindia', 
        type: 'relax', 
        folder: 'kindia', 
        sizes: { S: 58, M: 62, L: 78, XL: 90 }, 
        oneSeatArmSizes: { S: 58, M: 62, L: 78, XL: 90 }, 
        twoSeatSizes: { S: 132, M: 140, L: 172, XL: 196 },
        chaiseSizes: { S: 58, M: 62, L: 78, XL: 90 }, 
        armWidth: 16, 
        depth: 95, 
        chaiseDepth: 175, 
        cornerSize: 0, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'meiple'] 
    },
    'sting': { 
        name: 'Sting', 
        type: 'relax', 
        folder: 'sting', 
        sizes: { S: 62, M: 68, L: 78, XL: 88 }, 
        meridienSizes: { S: 114, M: 120, L: 130, XL: 140 },
        armWidth: 33, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 108, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', 'corner', 'chaise_l', 'chaise_r', 'meridien_l', 'meridien_r'] 
    },
    'kaori': { 
        name: 'Kaori', 
        type: 'fixed', 
        folder: 'kaori', 
        sizes: { S: 70, M: 80, L: 90, XL: 100 }, 
        chaiseSizes: { S: 70, M: 80, L: 90, XL: 100 },
        meipleSize: 70,
        armWidth: 12, 
        depth: 100, 
        chaiseDepth: 165, 
        cornerSize: 112, 
        modules: ['meiple', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'corner'] 
    },
    'polestar': { 
        name: 'Polestar', 
        type: 'fixed', 
        folder: 'polestar', 
        sizes: { L: 88 }, 
        twoSeatSizes: { L: 176 }, 
        chaiseSizes: { L: 88 }, 
        maxxiSize: 120, /* Largura assento Maxxi */
        maxxiDepth: 130, /* Profundidade Maxxi */
        pouffSize: 88,
        armWidth: 12, 
        depth: 90, 
        chaiseDepth: 174, 
        cornerSize: 100, 
        modules: ['seat_no_arm', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'corner', 'pouff', 'meiple', 'maxxi_l', 'maxxi_r'] 
    },
    'rinaldi': { 
        name: 'Rinaldi', 
        type: 'pendular', 
        folder: 'rinaldi', 
        hideSizeSelector: true, /* Ocultar seletor global pois mistura-se tamanhos */
        sizes: { L: 83, XL: 119 }, 
        armWidth: 40, 
        depth: 112,
        cornerSize: 112,
        pouffSize: 60,
        modules: ['rinaldi_seat_l', 'rinaldi_seat_xl', 'rinaldi_arm_l_l', 'rinaldi_arm_l_r', 'rinaldi_arm_xl_l', 'rinaldi_arm_xl_r', 'rinaldi_corner', 'rinaldi_pouff'] 
    },
    'spirit': { 
        name: 'Spirit', 
        type: 'fixed', 
        folder: 'spirit', 
        sizes: { L: 83, XL: 103 }, 
        chaiseSizes: { L: 83, XL: 103 },
        meridienSizes: 102,
        meridienDepth: 225,
        meipleSize: 80,
        armWidth: 14, 
        depth: 102, 
        chaiseDepth: 180, 
        cornerSize: 110, 
        modules: ['meiple', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'corner', 'meridien_l', 'meridien_r'] 
    },
    'rose': { 
        name: 'Rose', 
        type: 'fixed', 
        folder: 'rose', 
        sizes: { M: 72, L: 87 }, 
        chaiseSizes: { M: 72, L: 87 },
        meridienSizes: 92,
        meridienDepth: 212,
        meipleSize: 60,
        armWidth: 15, 
        depth: 92, 
        chaiseDepth: 165, 
        cornerSize: 105,
        modules: ['meiple', 'seat_arm_l', 'seat_arm_r', '2seats_arm_l', '2seats_arm_r', '2seats_2arms', 'chaise_l', 'chaise_r', 'corner', 'meridien_l', 'meridien_r'] 
    }
};